import { publicLocaleCodes, sanitizePublicCopy, type LocaleCode } from './locales'

export const docShiftToolSlugs = [
  'pdf-merge',
  'pdf-split',
  'pdf-rotate',
  'pdf-compressor',
  'pdf-watermark',
  'page-numbers',
  'metadata-cleaner',
  'text-to-pdf',
] as const

export type DocShiftToolSlug = (typeof docShiftToolSlugs)[number]
export type DocShiftToolCategory = 'organize' | 'edit' | 'optimize' | 'brand' | 'privacy' | 'convert'
export type DocShiftOperation = 'merge' | 'split' | 'rotate' | 'compress' | 'watermark' | 'page-numbers' | 'metadata' | 'text-to-pdf'

export interface ContentSection {
  heading: string
  paragraphs: string[]
}

export interface FaqItem {
  question: string
  answer: string
}

export interface DocShiftToolCopy {
  title: string
  shortName: string
  headline: string
  description: string
  resultLabel: string
  freeScope: string
  upgradeScope: string
  reviewedLabel: string
  contentSections: ContentSection[]
  faq: FaqItem[]
}

export interface DocShiftToolDefinition {
  slug: DocShiftToolSlug
  category: DocShiftToolCategory
  operation: DocShiftOperation
  requiresPdf: boolean
  acceptsMultiple: boolean
  usesTextInput: boolean
  defaultPages: string
  localized: Record<LocaleCode, DocShiftToolCopy>
}

export interface DocShiftRelatedTool {
  slug: DocShiftToolSlug
  title: string
  description: string
}

export interface DocShiftWorkflowStep {
  title: string
  body: string
}

export interface DocShiftToolInput {
  fileNames: string[]
  mimeTypes: string[]
  sizeBytes: number[]
  pageCount?: number
  pageSelection?: string
  rotationDegrees?: number
  watermarkText?: string
  metadataTitle?: string
  metadataAuthor?: string
  textContent?: string
}

export interface ResultMeta {
  label: string
  value: string
}

export interface DocShiftTransformPlan {
  slug: DocShiftToolSlug
  operation: DocShiftOperation
  outputName: string
  pageSelection: number[]
  rotationDegrees: 90 | 180 | 270
  watermarkText: string
  metadataTitle: string
  metadataAuthor: string
  textContent: string
  workerUsed: boolean
  warnings: string[]
  privacyNote: string
  upgradeGateNote: string
}

export interface DocShiftToolResult {
  ok: boolean
  output: string
  meta: ResultMeta[]
  plan?: DocShiftTransformPlan
  error?: string
}

interface DocShiftToolSpec {
  slug: DocShiftToolSlug
  category: DocShiftToolCategory
  operation: DocShiftOperation
  requiresPdf: boolean
  acceptsMultiple: boolean
  usesTextInput: boolean
  defaultPages: string
  title: string
  shortName: string
  headline: string
  description: string
  freeScope: string
  upgradeScope: string
}

const maxFreeBytes = 12 * 1024 * 1024
const maxFreeFiles = 5
const maxTextCharacters = 12_000
const maxPageNumber = 400
const allowedPdfMimeTypes = new Set(['application/pdf', 'application/x-pdf'])

const reviewed: Record<LocaleCode, string> = {
  en: 'Reviewed June 27, 2026',
  'pt-br': 'Revisado em 27 de junho de 2026',
  es: 'Revisado el 27 de junio de 2026',
  fr: 'Revise le 27 juin 2026',
  de: 'Geprueft am 27. Juni 2026',
}

const localizedBasics: Record<LocaleCode, {
  resultLabel: string
  localSection: string
  localBody: string
  workerSection: string
  workerBody: string
  gateSection: string
  gateBody: string
  faqStorage: FaqItem
  faqBatch: FaqItem
}> = {
  en: {
    resultLabel: 'Document preview',
    localSection: 'Local document data',
    localBody: 'The free MVP processes one small PDF workflow in the browser. File names, page text and generated bytes are not sent to a product API or analytics.',
    workerSection: 'Worker and PDF flow',
    workerBody: 'A browser worker validates file count, type, size and page-selection settings; pdf-lib runs in the browser tab to produce a downloadable PDF.',
    gateSection: 'Free limits and upgrade boundary',
    gateBody: 'Batch folders, larger files, OCR, table extraction, API, history, teams and server queues remain gated paid workflow features.',
    faqStorage: { question: 'Are my PDFs uploaded or stored?', answer: 'No. DocShift uses browser memory, ArrayBuffers and object URLs only; it does not use localStorage, sessionStorage or a product upload endpoint.' },
    faqBatch: { question: 'Can I process confidential contracts here?', answer: 'The free MVP is local, but it is not a legal redaction or archival system. Review sensitive documents before downloading or sharing output.' },
  },
  'pt-br': {
    resultLabel: 'Preview do documento',
    localSection: 'Dados locais do documento',
    localBody: 'O MVP gratuito processa um workflow pequeno de PDF no navegador. Nomes de arquivo, texto das paginas e bytes gerados nao sao enviados a API ou analytics.',
    workerSection: 'Fluxo worker e PDF',
    workerBody: 'Um worker valida quantidade, tipo, tamanho e selecao de paginas; pdf-lib roda na aba do navegador para gerar o PDF baixavel.',
    gateSection: 'Limites gratuitos e upgrade',
    gateBody: 'Lotes, pastas, arquivos maiores, OCR, extracao de tabelas, API, historico, equipes e filas no servidor seguem como workflow pago.',
    faqStorage: { question: 'Meus PDFs sao enviados ou armazenados?', answer: 'Nao. O DocShift usa memoria do navegador, ArrayBuffers e object URLs; nao usa localStorage, sessionStorage ou endpoint de upload.' },
    faqBatch: { question: 'Posso processar contratos confidenciais?', answer: 'O MVP gratuito e local, mas nao e sistema juridico de redacao ou arquivo. Revise documentos sensiveis antes de compartilhar a saida.' },
  },
  es: {
    resultLabel: 'Vista del documento',
    localSection: 'Datos locales',
    localBody: 'El MVP gratis procesa un flujo pequeno de PDF en el navegador. Nombres, texto de paginas y bytes generados no se envian a API ni analytics.',
    workerSection: 'Worker y PDF',
    workerBody: 'Un worker valida cantidad, tipo, tamano y seleccion de paginas; pdf-lib corre en la pestana para producir el PDF descargable.',
    gateSection: 'Limites gratis y upgrade',
    gateBody: 'Lotes, carpetas, archivos grandes, OCR, tablas, API, historial, equipos y colas servidor quedan como workflow pago.',
    faqStorage: { question: 'Se suben o guardan mis PDFs?', answer: 'No. DocShift usa memoria del navegador, ArrayBuffers y object URLs; no usa localStorage, sessionStorage ni endpoint de subida.' },
    faqBatch: { question: 'Puedo procesar contratos confidenciales?', answer: 'El MVP es local, pero no es un sistema legal de redaccion o archivo. Revisa documentos sensibles antes de compartir la salida.' },
  },
  fr: {
    resultLabel: 'Apercu document',
    localSection: 'Donnees locales',
    localBody: 'Le MVP gratuit traite un petit workflow PDF dans le navigateur. Noms, texte de page et octets generes ne partent pas vers une API ou analytics.',
    workerSection: 'Worker et PDF',
    workerBody: 'Un worker valide nombre, type, taille et pages; pdf-lib s execute dans l onglet pour produire le PDF a telecharger.',
    gateSection: 'Limites gratuites et offre payante',
    gateBody: 'Lots, dossiers, gros fichiers, OCR, tableaux, API, historique, equipes et queues serveur restent payants.',
    faqStorage: { question: 'Mes PDFs sont-ils envoyes ou stockes?', answer: 'Non. DocShift utilise memoire navigateur, ArrayBuffers et object URLs, sans localStorage, sessionStorage ni upload produit.' },
    faqBatch: { question: 'Puis-je traiter des contrats confidentiels?', answer: 'Le MVP est local, mais ce n est pas un systeme juridique de redaction ou d archivage. Relisez les documents sensibles avant partage.' },
  },
  de: {
    resultLabel: 'Dokumentvorschau',
    localSection: 'Lokale Dokumentdaten',
    localBody: 'Das kostenlose MVP verarbeitet einen kleinen PDF-Workflow im Browser. Dateinamen, Seitentext und erzeugte Bytes werden nicht an API oder Analytics gesendet.',
    workerSection: 'Worker und PDF',
    workerBody: 'Ein Worker validiert Anzahl, Typ, Groesse und Seitenauswahl; pdf-lib laeuft im Browser-Tab und erzeugt ein herunterladbares PDF.',
    gateSection: 'Kostenlose Limits und Upgrade',
    gateBody: 'Batch, Ordner, grosse Dateien, OCR, Tabellenextraktion, API, Verlauf, Teams und Server-Queues bleiben bezahlt.',
    faqStorage: { question: 'Werden PDFs hochgeladen oder gespeichert?', answer: 'Nein. DocShift nutzt Browser-Speicher, ArrayBuffers und Object URLs, kein localStorage, sessionStorage oder Upload-Endpunkt.' },
    faqBatch: { question: 'Kann ich vertrauliche Vertraege verarbeiten?', answer: 'Das MVP ist lokal, aber kein rechtliches Redaktions- oder Archivsystem. Pruefen Sie sensible Dokumente vor dem Teilen.' },
  },
}

const specs: DocShiftToolSpec[] = [
  {
    slug: 'pdf-merge',
    category: 'organize',
    operation: 'merge',
    requiresPdf: true,
    acceptsMultiple: true,
    usesTextInput: false,
    defaultPages: 'all',
    title: 'PDF Merge',
    shortName: 'Merge',
    headline: 'Combine up to five small PDFs in the browser and download one merged file.',
    description: 'Select PDFs in the order you want. DocShift copies pages locally and creates a single output PDF.',
    freeScope: 'Up to five PDFs and 12 MB total in the free browser-side MVP.',
    upgradeScope: 'Batch folders, larger files, saved ordering rules, API, teams and history.',
  },
  {
    slug: 'pdf-split',
    category: 'organize',
    operation: 'split',
    requiresPdf: true,
    acceptsMultiple: false,
    usesTextInput: false,
    defaultPages: '1',
    title: 'PDF Split',
    shortName: 'Split',
    headline: 'Extract selected pages from one PDF locally and download a smaller PDF.',
    description: 'Use page ranges such as 1-3,5. The free MVP creates one extracted output file.',
    freeScope: 'One PDF, selected pages and a local download without signup.',
    upgradeScope: 'Multiple output files, batch splitting, naming rules, storage history and API.',
  },
  {
    slug: 'pdf-rotate',
    category: 'edit',
    operation: 'rotate',
    requiresPdf: true,
    acceptsMultiple: false,
    usesTextInput: false,
    defaultPages: 'all',
    title: 'PDF Rotate',
    shortName: 'Rotate',
    headline: 'Rotate all pages or a selected page range by 90, 180 or 270 degrees.',
    description: 'Fix scanned pages or landscape pages in the browser, then download the adjusted PDF.',
    freeScope: 'One local rotate operation at a time.',
    upgradeScope: 'Batch rotate, detection rules, larger documents, API and team review.',
  },
  {
    slug: 'pdf-compressor',
    category: 'optimize',
    operation: 'compress',
    requiresPdf: true,
    acceptsMultiple: false,
    usesTextInput: false,
    defaultPages: 'all',
    title: 'PDF Compressor',
    shortName: 'Compress',
    headline: 'Rewrite a PDF with object streams and clean metadata for a lightweight local copy.',
    description: 'The free MVP performs safe browser-side structural cleanup. Image downsampling and OCR compression remain gated.',
    freeScope: 'One small PDF rewrite with no upload endpoint.',
    upgradeScope: 'Server-side compression profiles, larger files, OCR, queues, API and retention controls.',
  },
  {
    slug: 'pdf-watermark',
    category: 'brand',
    operation: 'watermark',
    requiresPdf: true,
    acceptsMultiple: false,
    usesTextInput: false,
    defaultPages: 'all',
    title: 'PDF Watermark',
    shortName: 'Watermark',
    headline: 'Add a light text watermark to every page or a selected page range locally.',
    description: 'Type a short label such as Draft, Internal or Client copy and download a watermarked PDF.',
    freeScope: 'One text watermark workflow with capped text length.',
    upgradeScope: 'Image watermarks, templates, batch branding, teams, API and approval flows.',
  },
  {
    slug: 'page-numbers',
    category: 'edit',
    operation: 'page-numbers',
    requiresPdf: true,
    acceptsMultiple: false,
    usesTextInput: false,
    defaultPages: 'all',
    title: 'PDF Page Numbers',
    shortName: 'Page numbers',
    headline: 'Add simple page numbers to a PDF in the browser without uploading it.',
    description: 'DocShift writes page numbers at the bottom of each selected page and preserves the result as a new PDF.',
    freeScope: 'One local page-numbering pass at a time.',
    upgradeScope: 'Custom templates, headers, footers, batch numbering, saved styles and API.',
  },
  {
    slug: 'metadata-cleaner',
    category: 'privacy',
    operation: 'metadata',
    requiresPdf: true,
    acceptsMultiple: false,
    usesTextInput: false,
    defaultPages: 'all',
    title: 'PDF Metadata Cleaner',
    shortName: 'Metadata',
    headline: 'Review and replace basic PDF title and author metadata locally.',
    description: 'Create a clean copy with controlled title and author fields. This is not forensic redaction.',
    freeScope: 'One metadata cleanup pass with visible privacy limits.',
    upgradeScope: 'Batch policies, audit reports, retention controls, server sandbox and API.',
  },
  {
    slug: 'text-to-pdf',
    category: 'convert',
    operation: 'text-to-pdf',
    requiresPdf: false,
    acceptsMultiple: false,
    usesTextInput: true,
    defaultPages: 'all',
    title: 'Text to PDF',
    shortName: 'Text to PDF',
    headline: 'Paste plain text and generate a simple PDF locally in your browser.',
    description: 'Use the free conversion tool for notes, drafts or small snippets without sending text to a backend.',
    freeScope: 'Plain-text conversion up to 12,000 characters in the browser.',
    upgradeScope: 'DOCX, images, OCR, templates, batch conversion, larger files, history and API.',
  },
]

const categoryLabels: Record<DocShiftToolCategory, Record<LocaleCode, string>> = {
  organize: { en: 'Organize', 'pt-br': 'Organizar', es: 'Organizar', fr: 'Organiser', de: 'Organisieren' },
  edit: { en: 'Edit', 'pt-br': 'Editar', es: 'Editar', fr: 'Editer', de: 'Bearbeiten' },
  optimize: { en: 'Optimize', 'pt-br': 'Otimizar', es: 'Optimizar', fr: 'Optimiser', de: 'Optimieren' },
  brand: { en: 'Brand', 'pt-br': 'Marca', es: 'Marca', fr: 'Marque', de: 'Branding' },
  privacy: { en: 'Privacy', 'pt-br': 'Privacidade', es: 'Privacidad', fr: 'Confidentialite', de: 'Datenschutz' },
  convert: { en: 'Convert', 'pt-br': 'Converter', es: 'Convertir', fr: 'Convertir', de: 'Konvertieren' },
}

function copyFor(spec: DocShiftToolSpec, locale: LocaleCode): DocShiftToolCopy {
  const base = localizedBasics[locale]

  return {
    title: spec.title,
    shortName: spec.shortName,
    headline: spec.headline,
    description: spec.description,
    resultLabel: base.resultLabel,
    freeScope: spec.freeScope,
    upgradeScope: spec.upgradeScope,
    reviewedLabel: reviewed[locale],
    contentSections: [
      { heading: base.localSection, paragraphs: [base.localBody] },
      { heading: base.workerSection, paragraphs: [base.workerBody] },
      { heading: base.gateSection, paragraphs: [base.gateBody] },
    ],
    faq: [base.faqStorage, base.faqBatch],
  }
}

function makeTool(spec: DocShiftToolSpec): DocShiftToolDefinition {
  return {
    slug: spec.slug,
    category: spec.category,
    operation: spec.operation,
    requiresPdf: spec.requiresPdf,
    acceptsMultiple: spec.acceptsMultiple,
    usesTextInput: spec.usesTextInput,
    defaultPages: spec.defaultPages,
    localized: Object.fromEntries(
      publicLocaleCodes.map((locale) => [locale, copyFor(spec, locale)]),
    ) as Record<LocaleCode, DocShiftToolCopy>,
  }
}

export const docShiftToolCatalog: DocShiftToolDefinition[] = specs.map(makeTool)
const toolBySlug = new Map(docShiftToolCatalog.map((tool) => [tool.slug, tool]))
const relatedBySlug: Record<DocShiftToolSlug, DocShiftToolSlug[]> = {
  'pdf-merge': ['pdf-split', 'page-numbers', 'pdf-compressor'],
  'pdf-split': ['pdf-merge', 'pdf-rotate', 'metadata-cleaner'],
  'pdf-rotate': ['page-numbers', 'pdf-watermark', 'pdf-compressor'],
  'pdf-compressor': ['metadata-cleaner', 'pdf-merge', 'pdf-split'],
  'pdf-watermark': ['page-numbers', 'metadata-cleaner', 'pdf-merge'],
  'page-numbers': ['pdf-watermark', 'pdf-rotate', 'pdf-merge'],
  'metadata-cleaner': ['pdf-compressor', 'pdf-watermark', 'pdf-split'],
  'text-to-pdf': ['pdf-watermark', 'page-numbers', 'metadata-cleaner'],
}

const workflowStepsBySlug: Record<DocShiftToolSlug, DocShiftWorkflowStep[]> = {
  'pdf-merge': [
    { title: 'Choose PDFs in order', body: 'Select up to five small PDF files and keep the order clear before processing.' },
    { title: 'Validate locally', body: 'Worker validation checks file count, type and total size before pdf-lib copies pages.' },
    { title: 'Download one output', body: 'The merged file is created in the browser and never sent to a product upload API.' },
  ],
  'pdf-split': [
    { title: 'Choose pages', body: 'Use a range such as 1-3,5 to extract the pages you need from one file.' },
    { title: 'Preview the plan', body: 'The workflow snapshot shows selected pages and expected output before download.' },
    { title: 'Batch later', body: 'Multiple split files, naming rules and history stay gated paid workflow value.' },
  ],
  'pdf-rotate': [
    { title: 'Pick page scope', body: 'Rotate all pages or a bounded page range by 90, 180 or 270 degrees.' },
    { title: 'Fix scans locally', body: 'pdf-lib rewrites page rotation in browser memory with no server upload.' },
    { title: 'Detection gated', body: 'Auto-detection and batch rotation require server-side gates before activation.' },
  ],
  'pdf-compressor': [
    { title: 'Rewrite safely', body: 'The free tool performs a browser-side structure rewrite and metadata normalization.' },
    { title: 'Avoid false claims', body: 'Image downsampling, OCR compression and deep optimization are not active.' },
    { title: 'Server profiles gated', body: 'Large-file queues and compression profiles require sandbox, antivirus and retention controls.' },
  ],
  'pdf-watermark': [
    { title: 'Enter a short label', body: 'Use a concise text watermark such as Draft, Internal or Client copy.' },
    { title: 'Apply to pages', body: 'DocShift writes a light text mark to each selected page in the browser.' },
    { title: 'Brand templates gated', body: 'Image watermarks, templates, approvals and batch branding stay upgrade scope.' },
  ],
  'page-numbers': [
    { title: 'Choose page scope', body: 'Add simple page numbers to the selected pages of one local PDF.' },
    { title: 'Keep output separate', body: 'The source file is not modified; DocShift generates a new downloadable PDF.' },
    { title: 'Templates gated', body: 'Headers, footers, saved styles and API numbering remain paid workflow scope.' },
  ],
  'metadata-cleaner': [
    { title: 'Set visible fields', body: 'Replace basic PDF title and author metadata in a clean local copy.' },
    { title: 'Know the limit', body: 'This does not remove visible page content or guarantee forensic redaction.' },
    { title: 'Policy reports gated', body: 'Audit reports, retention controls and batch policies remain gated.' },
  ],
  'text-to-pdf': [
    { title: 'Paste plain text', body: 'Generate a simple local PDF from notes, drafts or checklists up to the free character limit.' },
    { title: 'Create locally', body: 'pdf-lib builds the document in the browser without sending text to a backend.' },
    { title: 'Templates gated', body: 'DOCX, OCR, branded templates, history and API conversion stay upgrade scope.' },
  ],
}

export function getDocShiftToolBySlug(slug: string | undefined): DocShiftToolDefinition | null {
  if (!docShiftToolSlugs.includes(slug as DocShiftToolSlug)) {
    return null
  }

  return toolBySlug.get(slug as DocShiftToolSlug) ?? null
}

export function getDocShiftToolCopy(tool: DocShiftToolDefinition, locale: LocaleCode): DocShiftToolCopy {
  return sanitizePublicCopy(locale, tool.localized[locale])
}

export function getRelatedDocShiftTools(slug: DocShiftToolSlug, locale: LocaleCode): DocShiftRelatedTool[] {
  return relatedBySlug[slug]
    .map((relatedSlug) => getDocShiftToolBySlug(relatedSlug))
    .filter((tool): tool is DocShiftToolDefinition => Boolean(tool))
    .map((tool) => {
      const copy = getDocShiftToolCopy(tool, locale)

      return {
        slug: tool.slug,
        title: copy.title,
        description: copy.freeScope,
      }
    })
}

export function getDocShiftWorkflowSteps(slug: DocShiftToolSlug, locale: LocaleCode = 'en'): DocShiftWorkflowStep[] {
  return sanitizePublicCopy(locale, workflowStepsBySlug[slug])
}

export function getCategoryLabel(category: DocShiftToolCategory, locale: LocaleCode): string {
  return categoryLabels[category][locale]
}

export function filterDocShiftTools(query: string, category: DocShiftToolCategory | 'all', locale: LocaleCode): DocShiftToolDefinition[] {
  const normalizedQuery = query.trim().toLowerCase()

  return docShiftToolCatalog.filter((tool) => {
    const copy = getDocShiftToolCopy(tool, locale)
    const matchesCategory = category === 'all' || tool.category === category
    const searchableText = [
      tool.slug,
      tool.operation,
      getCategoryLabel(tool.category, locale),
      copy.title,
      copy.shortName,
      copy.headline,
      copy.description,
      copy.freeScope,
      copy.upgradeScope,
    ].join(' ').toLowerCase()

    return matchesCategory && (!normalizedQuery || searchableText.includes(normalizedQuery))
  })
}

export function createDocShiftToolStructuredData(tool: DocShiftToolDefinition, locale: LocaleCode, url: string): Record<string, unknown>[] {
  const copy = getDocShiftToolCopy(tool, locale)

  return [
    {
      '@context': 'https://schema.org',
      '@type': 'WebApplication',
      name: copy.title,
      applicationCategory: 'ProductivityApplication',
      operatingSystem: 'Any',
      url,
      isAccessibleForFree: true,
      offers: {
        '@type': 'Offer',
        price: '0',
        priceCurrency: 'USD',
      },
      description: copy.headline,
      featureList: [
        copy.freeScope,
        'Browser-side PDF processing',
        'No product upload endpoint in the free MVP',
      ],
    },
    {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: copy.faq.map((item) => ({
        '@type': 'Question',
        name: item.question,
        acceptedAnswer: {
          '@type': 'Answer',
          text: item.answer,
        },
      })),
    },
  ]
}

function fail(error: string): DocShiftToolResult {
  return { ok: false, output: '', meta: [], error }
}

function baseName(value: string): string {
  return value
    .replace(/\.[a-z0-9]+$/i, '')
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '') || 'docshift-document'
}

export function formatBytes(bytes: number): string {
  if (bytes < 1024) {
    return `${bytes} B`
  }

  if (bytes < 1024 * 1024) {
    return `${(bytes / 1024).toFixed(1)} KB`
  }

  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`
}

function normalizeFileNames(value: string[]): string[] {
  return value.map((item) => item.trim()).filter(Boolean)
}

function hasPdfExtension(fileName: string): boolean {
  return /\.pdf$/i.test(fileName)
}

function validatePdfInputs(tool: DocShiftToolDefinition, input: DocShiftToolInput): void {
  if (!tool.requiresPdf) {
    return
  }

  const fileNames = normalizeFileNames(input.fileNames)
  if (fileNames.length === 0) {
    throw new Error('Choose a PDF file before processing.')
  }

  if (!tool.acceptsMultiple && fileNames.length > 1) {
    throw new Error('This free tool accepts one PDF at a time.')
  }

  if (fileNames.length > maxFreeFiles) {
    throw new Error(`Free DocShift merge accepts at most ${maxFreeFiles} PDFs.`)
  }

  const totalBytes = input.sizeBytes.reduce((sum, value) => sum + value, 0)
  if (totalBytes <= 0 || totalBytes > maxFreeBytes) {
    throw new Error(`Free DocShift files must total at most ${formatBytes(maxFreeBytes)}.`)
  }

  for (let index = 0; index < fileNames.length; index += 1) {
    const mimeType = (input.mimeTypes[index] ?? '').toLowerCase()
    if (!allowedPdfMimeTypes.has(mimeType) && !hasPdfExtension(fileNames[index])) {
      throw new Error('DocShift accepts PDF files only in the free document MVP.')
    }
  }
}

function normalizeRotation(value: unknown): 90 | 180 | 270 {
  const parsed = Number(value ?? 90)
  return parsed === 180 || parsed === 270 ? parsed : 90
}

function sanitizeShortText(value: unknown, fallback: string, limit: number): string {
  const normalized = String(value ?? '').replace(/\s+/g, ' ').trim()
  if (!normalized) {
    return fallback
  }

  return normalized.slice(0, limit)
}

export function parsePageSelection(value: string | undefined, pageCount: number): number[] {
  if (!Number.isInteger(pageCount) || pageCount <= 0 || pageCount > maxPageNumber) {
    return []
  }

  const source = (value ?? '').trim().toLowerCase()
  if (!source || source === 'all') {
    return Array.from({ length: pageCount }, (_, index) => index)
  }

  const selected = new Set<number>()
  for (const part of source.split(',')) {
    const token = part.trim()
    if (!token) {
      continue
    }

    const range = token.match(/^(\d+)\s*-\s*(\d+)$/)
    if (range) {
      const start = Number(range[1])
      const end = Number(range[2])
      const min = Math.min(start, end)
      const max = Math.max(start, end)
      for (let page = min; page <= max; page += 1) {
        if (page >= 1 && page <= pageCount) {
          selected.add(page - 1)
        }
      }
      continue
    }

    const page = Number(token)
    if (Number.isInteger(page) && page >= 1 && page <= pageCount) {
      selected.add(page - 1)
    }
  }

  return [...selected].sort((a, b) => a - b)
}

export function estimateOutputBytesForPlan(plan: DocShiftTransformPlan, input: DocShiftToolInput): number {
  const totalBytes = input.sizeBytes.reduce((sum, value) => sum + value, 0)
  if (plan.operation === 'text-to-pdf') {
    return Math.max(1_800, Math.round(plan.textContent.length * 8))
  }

  if (plan.operation === 'split' && input.pageCount && plan.pageSelection.length > 0) {
    return Math.max(1_200, Math.round(totalBytes * (plan.pageSelection.length / input.pageCount)))
  }

  if (plan.operation === 'compress' || plan.operation === 'metadata') {
    return Math.max(1_200, Math.round(totalBytes * 0.92))
  }

  return Math.max(1_200, totalBytes || 1_200)
}

function outputNameFor(tool: DocShiftToolDefinition, input: DocShiftToolInput): string {
  if (tool.operation === 'text-to-pdf') {
    return 'docshift-text-to-pdf.pdf'
  }

  const name = baseName(normalizeFileNames(input.fileNames)[0] ?? 'document')
  return `${name}-${tool.slug}.pdf`
}

export function planDocShiftTransform(slug: DocShiftToolSlug, input: DocShiftToolInput, workerUsed = false): DocShiftToolResult {
  try {
    const tool = getDocShiftToolBySlug(slug)
    if (!tool) {
      return fail('Tool not found.')
    }

    validatePdfInputs(tool, input)

    const pageCount = Math.min(Math.max(Number(input.pageCount ?? 1), 1), maxPageNumber)
    const pageSelection = parsePageSelection(input.pageSelection ?? tool.defaultPages, pageCount)
    const warnings: string[] = []
    const textContent = String(input.textContent ?? '').trim()

    if (tool.operation === 'text-to-pdf') {
      if (textContent.length === 0) {
        throw new Error('Paste plain text before generating a PDF.')
      }

      if (textContent.length > maxTextCharacters) {
        throw new Error(`Text to PDF is limited to ${maxTextCharacters.toLocaleString('en-US')} characters in the free MVP.`)
      }
    }

    if (tool.operation === 'split' && pageSelection.length === 0) {
      throw new Error('Choose at least one valid page number or range.')
    }

    if (tool.operation === 'merge' && normalizeFileNames(input.fileNames).length === 1) {
      warnings.push('Only one PDF is selected. Add more files to combine documents.')
    }

    if (tool.operation === 'compress') {
      warnings.push('Browser-side compression is a safe structure rewrite, not image downsampling or OCR compression.')
    }

    if (tool.operation === 'metadata') {
      warnings.push('Metadata cleanup is not forensic redaction. Visible page content is not removed.')
    }

    const plan: DocShiftTransformPlan = {
      slug,
      operation: tool.operation,
      outputName: outputNameFor(tool, input),
      pageSelection,
      rotationDegrees: normalizeRotation(input.rotationDegrees),
      watermarkText: sanitizeShortText(input.watermarkText, 'Draft', 64),
      metadataTitle: sanitizeShortText(input.metadataTitle, 'DocShift output', 90),
      metadataAuthor: sanitizeShortText(input.metadataAuthor, 'DocShift local tool', 90),
      textContent,
      workerUsed,
      warnings,
      privacyNote: 'Processed locally in this browser session; no upload endpoint, localStorage or sessionStorage is used.',
      upgradeGateNote: 'Batch jobs, larger files, OCR, table extraction, history, API, teams and server queues remain gated.',
    }

    return {
      ok: true,
      output: plan.outputName,
      meta: [
        { label: 'Input files', value: String(tool.operation === 'text-to-pdf' ? 0 : normalizeFileNames(input.fileNames).length) },
        { label: 'Input total', value: formatBytes(input.sizeBytes.reduce((sum, value) => sum + value, 0)) },
        { label: 'Pages planned', value: tool.operation === 'text-to-pdf' ? 'new PDF' : String(plan.pageSelection.length || pageCount) },
        { label: 'Estimated output', value: formatBytes(estimateOutputBytesForPlan(plan, input)) },
      ],
      plan,
    }
  } catch (error) {
    return fail(error instanceof Error ? error.message : 'Document plan failed.')
  }
}
