$ErrorActionPreference = "Stop"

$requiredPaths = @(
    "AGENTS.md",
    "README.md",
    ".gitignore",
    ".github/workflows/quality-gate.yml",
    ".github/workflows/deploy-dry-run.yml",
    ".github/workflows/deploy-supersite-hostgator.yml",
    ".github/workflows/deploy-netprobe-hostgator.yml",
    ".github/workflows/deploy-control-plane-hostgator.yml",
    "package.json",
    "playwright.config.ts",
    "playwright.netprobe.config.ts",
    "playwright.calcharbor.config.ts",
    "playwright.devutility.config.ts",
    "playwright.timenexus.config.ts",
    "playwright.qrroute.config.ts",
    "playwright.invoicecraft.config.ts",
    "playwright.mailhealth.config.ts",
    "playwright.sitepulse.config.ts",
    "playwright.pixelbatch.config.ts",
    "playwright.docshift.config.ts",
    "pnpm-workspace.yaml",
    "pnpm-lock.yaml",
    "docs/MEGA_PROMPT_SUPERSITES.md",
    "docs/OPERATING_CONTEXT.md",
    "docs/STATUS.md",
    "docs/ROADMAP.md",
    "docs/ARCHITECTURE.md",
    "docs/SECURITY.md",
    "docs/DATA_GOVERNANCE.md",
    "docs/SEO_AIO_PLAYBOOK.md",
    "docs/ADSENSE_PLAYBOOK.md",
    "docs/ANALYTICS.md",
    "docs/BILLING.md",
    "docs/METRICS.md",
    "docs/HUMAN_ACTION_REQUIRED.md",
    "docs/ADR/0008-ci-cd-dry-run-foundation.md",
    "docs/ADR/0009-shared-foundation-packages.md",
    "docs/ADR/0010-control-plane-api-foundation.md",
    "docs/ADR/0011-control-plane-blade-mvp.md",
    "docs/ADR/0012-analytics-event-contract.md",
    "docs/RUNBOOKS/CI_CD.md",
    "docs/RUNBOOKS/SPRINT_EXECUTION.md",
    "docs/RUNBOOKS/VPS_RUNTIME.md",
    "docs/ADR/0007-vps-runtime-isolation.md",
    "apps/supersite",
    "apps/supersite/package.json",
    "apps/supersite/nuxt.config.ts",
    "apps/supersite/app/app.vue",
    "apps/supersite/app/components/CatalogHome.vue",
    "apps/supersite/app/components/LegalFooter.vue",
    "apps/supersite/app/components/LanguageNav.vue",
    "apps/supersite/app/components/SiteHeader.vue",
    "apps/supersite/app/data/copy.ts",
    "apps/supersite/app/data/legal.ts",
    "apps/supersite/app/data/locales.ts",
    "apps/supersite/app/data/routes.ts",
    "apps/supersite/app/data/sites.ts",
    "apps/supersite/app/utils/analytics.ts",
    "apps/supersite/app/pages/index.vue",
    "apps/supersite/app/pages/[locale]/[page].vue",
    "apps/supersite/app/pages/[locale]/index.vue",
    "apps/supersite/app/pages/[locale]/sites/[slug].vue",
    "apps/supersite/server/routes/sitemap.xml.ts",
    "apps/supersite/tests/catalog.test.ts",
    "tests/e2e/supersite.spec.ts",
    "apps/control-plane",
    "apps/control-plane/artisan",
    "apps/control-plane/composer.json",
    "apps/control-plane/composer.lock",
    "apps/control-plane/bootstrap/app.php",
    "apps/control-plane/routes/api.php",
    "apps/control-plane/routes/web.php",
    "apps/control-plane/app/Http/Controllers/Admin/DashboardController.php",
    "apps/control-plane/app/Http/Controllers/Admin/SiteController.php",
    "apps/control-plane/app/Http/Controllers/Api/V1/CurrentUserController.php",
    "apps/control-plane/app/Http/Controllers/Api/V1/AnalyticsEventController.php",
    "apps/control-plane/app/Http/Controllers/Api/V1/MetricSnapshotIndexController.php",
    "apps/control-plane/app/Http/Controllers/Api/V1/NetProbe/ClientIpController.php",
    "apps/control-plane/app/Http/Controllers/Api/V1/NetProbe/DnsPropagationController.php",
    "apps/control-plane/app/Http/Controllers/Api/V1/NetProbe/DnsLookupController.php",
    "apps/control-plane/app/Http/Controllers/Api/V1/NetProbe/PortCheckController.php",
    "apps/control-plane/app/Http/Controllers/Api/V1/NetProbe/RdapLookupController.php",
    "apps/control-plane/app/Http/Controllers/Api/V1/NetProbe/ReachabilityController.php",
    "apps/control-plane/app/Http/Controllers/Api/V1/NetProbe/SslCertificateController.php",
    "apps/control-plane/app/Http/Controllers/Api/V1/SiteIndexController.php",
    "apps/control-plane/app/Http/Controllers/Auth/AuthenticatedSessionController.php",
    "apps/control-plane/app/Http/Middleware/EnsurePermission.php",
    "apps/control-plane/app/Models/AuditLog.php",
    "apps/control-plane/app/Models/AnalyticsEvent.php",
    "apps/control-plane/app/Models/AiGrowthAnomaly.php",
    "apps/control-plane/app/Models/AiGrowthAudit.php",
    "apps/control-plane/app/Models/AiGrowthRecommendation.php",
    "apps/control-plane/app/Models/DeploymentRecord.php",
    "apps/control-plane/app/Models/Incident.php",
    "apps/control-plane/app/Models/MetricSnapshot.php",
    "apps/control-plane/app/Models/OperationalTask.php",
    "apps/control-plane/app/Models/Permission.php",
    "apps/control-plane/app/Models/Role.php",
    "apps/control-plane/app/Models/Site.php",
    "apps/control-plane/database/factories/SiteFactory.php",
    "apps/control-plane/database/migrations/2026_06_26_000100_create_sites_table.php",
    "apps/control-plane/database/migrations/2026_06_26_000110_create_access_control_tables.php",
    "apps/control-plane/database/migrations/2026_06_26_000120_create_audit_logs_table.php",
    "apps/control-plane/database/migrations/2026_06_26_000130_create_operational_tables.php",
    "apps/control-plane/database/migrations/2026_06_26_000140_create_analytics_tables.php",
    "apps/control-plane/database/migrations/2026_06_27_000200_create_ai_growth_tables.php",
    "apps/control-plane/app/Support/Analytics/AnalyticsEventSanitizer.php",
    "apps/control-plane/app/Support/NetProbe/DnsPropagationService.php",
    "apps/control-plane/app/Support/NetProbe/DnsLookupService.php",
    "apps/control-plane/app/Support/NetProbe/HttpNetProbeRdapClient.php",
    "apps/control-plane/app/Support/NetProbe/NetProbeCertificateProbe.php",
    "apps/control-plane/app/Support/NetProbe/NetProbeDnsResolver.php",
    "apps/control-plane/app/Support/NetProbe/NetProbeHostGuard.php",
    "apps/control-plane/app/Support/NetProbe/NetProbeRdapClient.php",
    "apps/control-plane/app/Support/NetProbe/NetProbeTcpProbe.php",
    "apps/control-plane/app/Support/NetProbe/PhpNetProbeCertificateProbe.php",
    "apps/control-plane/app/Support/NetProbe/PhpNetProbeDnsResolver.php",
    "apps/control-plane/app/Support/NetProbe/PhpNetProbeTcpProbe.php",
    "apps/control-plane/app/Support/NetProbe/PortCheckService.php",
    "apps/control-plane/app/Support/NetProbe/RdapLookupService.php",
    "apps/control-plane/app/Support/NetProbe/ReachabilityService.php",
    "apps/control-plane/app/Support/NetProbe/SslCertificateService.php",
    "apps/control-plane/database/seeders/AccessControlSeeder.php",
    "apps/control-plane/database/seeders/AiGrowthReadinessSeeder.php",
    "apps/control-plane/database/seeders/DeploymentRecordSeeder.php",
    "apps/control-plane/database/seeders/OperationalTaskSeeder.php",
    "apps/control-plane/database/seeders/PortfolioSiteSeeder.php",
    "apps/control-plane/resources/views/admin/dashboard.blade.php",
    "apps/control-plane/resources/views/admin/sites/create.blade.php",
    "apps/control-plane/resources/views/admin/sites/edit.blade.php",
    "apps/control-plane/resources/views/admin/sites/index.blade.php",
    "apps/control-plane/resources/views/auth/login.blade.php",
    "apps/control-plane/resources/views/layouts/admin.blade.php",
    "apps/control-plane/resources/views/welcome.blade.php",
    "apps/control-plane/tests/Feature/AdminPanelTest.php",
    "apps/control-plane/tests/Feature/AnalyticsApiTest.php",
    "apps/control-plane/tests/Feature/HealthTest.php",
    "apps/control-plane/tests/Feature/NetProbeApiTest.php",
    "apps/control-plane/tests/Feature/ControlPlaneApiTest.php",
    "apps/netprobe-atlas",
    "apps/calcharbor",
    "apps/devutility-lab",
    "apps/timenexus",
    "apps/qrroute",
    "apps/invoicecraft",
    "apps/mailhealth",
    "apps/sitepulse-lab",
    "apps/pixelbatch",
    "apps/docshift",
    "packages/ui",
    "packages/ui/package.json",
    "packages/ui/tsconfig.json",
    "packages/ui/src/index.ts",
    "packages/ui/tests/ui.test.ts",
    "packages/seo",
    "packages/seo/package.json",
    "packages/seo/tsconfig.json",
    "packages/seo/src/index.ts",
    "packages/seo/tests/seo.test.ts",
    "packages/i18n",
    "packages/i18n/package.json",
    "packages/i18n/tsconfig.json",
    "packages/i18n/src/index.ts",
    "packages/i18n/tests/i18n.test.ts",
    "packages/analytics",
    "packages/analytics/package.json",
    "packages/analytics/tsconfig.json",
    "packages/analytics/src/index.ts",
    "packages/analytics/tests/analytics.test.ts",
    "packages/ads",
    "packages/ads/package.json",
    "packages/ads/tsconfig.json",
    "packages/ads/src/index.ts",
    "packages/ads/tests/ads.test.ts",
    "packages/consent",
    "packages/consent/package.json",
    "packages/consent/tsconfig.json",
    "packages/consent/src/index.ts",
    "packages/consent/tests/consent.test.ts",
    "packages/auth",
    "packages/billing",
    "packages/billing/package.json",
    "packages/billing/tsconfig.json",
    "packages/billing/src/index.ts",
    "packages/billing/tests/billing.test.ts",
    "packages/cms",
    "packages/ai-growth",
    "packages/ai-growth/package.json",
    "packages/ai-growth/tsconfig.json",
    "packages/ai-growth/src/index.ts",
    "packages/ai-growth/tests/ai-growth.test.ts",
    "packages/security",
    "packages/testing",
    "infra/docker/compose.local.yml",
    "infra/deployment/apps.json",
    "infra/deployment/README.md",
    "infra/environments/local/databases.md",
    "infra/environments/production/hostgator/README.md",
    "infra/environments/production/vps/README.md",
    "scripts/hostgator-bootstrap.ps1",
    "scripts/build-netprobe-hostgator-artifact.ps1",
    "scripts/build-control-plane-hostgator-artifact.ps1",
    "scripts/build-supersite-hostgator-artifact.ps1",
    "scripts/ci-detect-changes.ps1",
    "scripts/prepare-deploy-dry-run.ps1",
    "scripts/publish-netprobe-hostgator.ps1",
    "scripts/publish-control-plane-hostgator.ps1",
    "scripts/publish-supersite-hostgator.ps1",
    "scripts/smoke-control-plane-public.ps1",
    "scripts/smoke-netprobe-public.ps1",
    "scripts/smoke-supersite-public.ps1",
    "scripts/sync-github-environments.ps1",
    "scripts/validate-hostgator-bootstrap.ps1",
    "scripts/validate-control-plane-artifact.ps1",
    "scripts/validate-netprobe-preview.ps1",
    "scripts/validate-supersite-preview.ps1",
    "scripts/validate-vps-runtime.ps1"
)

$netprobePaths = @(
    "apps/netprobe-atlas/package.json",
    "apps/netprobe-atlas/nuxt.config.ts",
    "apps/netprobe-atlas/app/app.vue",
    "apps/netprobe-atlas/app/components/LanguageNav.vue",
    "apps/netprobe-atlas/app/components/LegalFooter.vue",
    "apps/netprobe-atlas/app/components/NetProbeHome.vue",
    "apps/netprobe-atlas/app/components/SiteHeader.vue",
    "apps/netprobe-atlas/app/data/copy.ts",
    "apps/netprobe-atlas/app/data/locales.ts",
    "apps/netprobe-atlas/app/data/pages.ts",
    "apps/netprobe-atlas/app/data/routes.ts",
    "apps/netprobe-atlas/app/data/tools.ts",
    "apps/netprobe-atlas/app/pages/index.vue",
    "apps/netprobe-atlas/app/pages/[locale]/[page].vue",
    "apps/netprobe-atlas/app/pages/[locale]/index.vue",
    "apps/netprobe-atlas/app/pages/[locale]/tools/[slug].vue",
    "apps/netprobe-atlas/app/utils/analytics.ts",
    "apps/netprobe-atlas/server/routes/sitemap.xml.ts",
    "apps/netprobe-atlas/tests/netprobe.test.ts",
    "tests/e2e/netprobe.spec.ts"
)

$requiredPaths += $netprobePaths

$calcharborPaths = @(
    "apps/calcharbor/package.json",
    "apps/calcharbor/nuxt.config.ts",
    "apps/calcharbor/app/app.vue",
    "apps/calcharbor/app/components/CalcHarborHome.vue",
    "apps/calcharbor/app/components/LanguageNav.vue",
    "apps/calcharbor/app/components/LegalFooter.vue",
    "apps/calcharbor/app/components/SiteHeader.vue",
    "apps/calcharbor/app/data/calculators.ts",
    "apps/calcharbor/app/data/copy.ts",
    "apps/calcharbor/app/data/locales.ts",
    "apps/calcharbor/app/data/pages.ts",
    "apps/calcharbor/app/data/routes.ts",
    "apps/calcharbor/app/pages/index.vue",
    "apps/calcharbor/app/pages/[locale]/[page].vue",
    "apps/calcharbor/app/pages/[locale]/index.vue",
    "apps/calcharbor/app/pages/[locale]/calculators/[slug].vue",
    "apps/calcharbor/app/utils/analytics.ts",
    "apps/calcharbor/server/routes/sitemap.xml.ts",
    "apps/calcharbor/tests/calcharbor.test.ts",
    "tests/e2e/calcharbor.spec.ts",
    "scripts/validate-calcharbor-preview.ps1"
)

$requiredPaths += $calcharborPaths

$devutilityPaths = @(
    "apps/devutility-lab/package.json",
    "apps/devutility-lab/nuxt.config.ts",
    "apps/devutility-lab/app/app.vue",
    "apps/devutility-lab/app/components/DevUtilityHome.vue",
    "apps/devutility-lab/app/components/LanguageNav.vue",
    "apps/devutility-lab/app/components/LegalFooter.vue",
    "apps/devutility-lab/app/components/SiteHeader.vue",
    "apps/devutility-lab/app/data/copy.ts",
    "apps/devutility-lab/app/data/locales.ts",
    "apps/devutility-lab/app/data/pages.ts",
    "apps/devutility-lab/app/data/routes.ts",
    "apps/devutility-lab/app/data/tools.ts",
    "apps/devutility-lab/app/pages/index.vue",
    "apps/devutility-lab/app/pages/[locale]/[page].vue",
    "apps/devutility-lab/app/pages/[locale]/index.vue",
    "apps/devutility-lab/app/pages/[locale]/tools/[slug].vue",
    "apps/devutility-lab/app/utils/analytics.ts",
    "apps/devutility-lab/app/utils/toolWorker.ts",
    "apps/devutility-lab/app/workers/devutility.worker.ts",
    "apps/devutility-lab/server/routes/sitemap.xml.ts",
    "apps/devutility-lab/tests/devutility.test.ts",
    "tests/e2e/devutility.spec.ts",
    "scripts/validate-devutility-preview.ps1"
)

$requiredPaths += $devutilityPaths

$timenexusPaths = @(
    "apps/timenexus/package.json",
    "apps/timenexus/nuxt.config.ts",
    "apps/timenexus/app/app.vue",
    "apps/timenexus/app/components/TimeNexusHome.vue",
    "apps/timenexus/app/components/LanguageNav.vue",
    "apps/timenexus/app/components/LegalFooter.vue",
    "apps/timenexus/app/components/SiteHeader.vue",
    "apps/timenexus/app/data/copy.ts",
    "apps/timenexus/app/data/locales.ts",
    "apps/timenexus/app/data/pages.ts",
    "apps/timenexus/app/data/routes.ts",
    "apps/timenexus/app/data/tools.ts",
    "apps/timenexus/app/pages/index.vue",
    "apps/timenexus/app/pages/[locale]/[page].vue",
    "apps/timenexus/app/pages/[locale]/index.vue",
    "apps/timenexus/app/pages/[locale]/tools/[slug].vue",
    "apps/timenexus/app/utils/analytics.ts",
    "apps/timenexus/app/utils/timeWorker.ts",
    "apps/timenexus/app/workers/timenexus.worker.ts",
    "apps/timenexus/server/routes/sitemap.xml.ts",
    "apps/timenexus/tests/timenexus.test.ts",
    "tests/e2e/timenexus.spec.ts",
    "scripts/validate-timenexus-preview.ps1"
)

$requiredPaths += $timenexusPaths

$qrroutePaths = @(
    "apps/qrroute/package.json",
    "apps/qrroute/nuxt.config.ts",
    "apps/qrroute/app/app.vue",
    "apps/qrroute/app/components/QRRouteHome.vue",
    "apps/qrroute/app/components/LanguageNav.vue",
    "apps/qrroute/app/components/LegalFooter.vue",
    "apps/qrroute/app/components/SiteHeader.vue",
    "apps/qrroute/app/data/copy.ts",
    "apps/qrroute/app/data/locales.ts",
    "apps/qrroute/app/data/pages.ts",
    "apps/qrroute/app/data/routes.ts",
    "apps/qrroute/app/data/tools.ts",
    "apps/qrroute/app/pages/index.vue",
    "apps/qrroute/app/pages/[locale]/[page].vue",
    "apps/qrroute/app/pages/[locale]/index.vue",
    "apps/qrroute/app/pages/[locale]/tools/[slug].vue",
    "apps/qrroute/app/utils/analytics.ts",
    "apps/qrroute/app/utils/qrrouteWorker.ts",
    "apps/qrroute/app/workers/qrroute.worker.ts",
    "apps/qrroute/server/routes/sitemap.xml.ts",
    "apps/qrroute/tests/qrroute.test.ts",
    "tests/e2e/qrroute.spec.ts",
    "scripts/validate-qrroute-preview.ps1"
)

$requiredPaths += $qrroutePaths

$invoicecraftPaths = @(
    "apps/invoicecraft/package.json",
    "apps/invoicecraft/nuxt.config.ts",
    "apps/invoicecraft/app/app.vue",
    "apps/invoicecraft/app/components/InvoiceCraftHome.vue",
    "apps/invoicecraft/app/components/LanguageNav.vue",
    "apps/invoicecraft/app/components/LegalFooter.vue",
    "apps/invoicecraft/app/components/SiteHeader.vue",
    "apps/invoicecraft/app/data/copy.ts",
    "apps/invoicecraft/app/data/locales.ts",
    "apps/invoicecraft/app/data/pages.ts",
    "apps/invoicecraft/app/data/routes.ts",
    "apps/invoicecraft/app/data/tools.ts",
    "apps/invoicecraft/app/pages/index.vue",
    "apps/invoicecraft/app/pages/[locale]/[page].vue",
    "apps/invoicecraft/app/pages/[locale]/index.vue",
    "apps/invoicecraft/app/pages/[locale]/tools/[slug].vue",
    "apps/invoicecraft/app/utils/analytics.ts",
    "apps/invoicecraft/app/utils/invoicecraftWorker.ts",
    "apps/invoicecraft/app/workers/invoicecraft.worker.ts",
    "apps/invoicecraft/server/routes/sitemap.xml.ts",
    "apps/invoicecraft/tests/invoicecraft.test.ts",
    "tests/e2e/invoicecraft.spec.ts",
    "scripts/validate-invoicecraft-preview.ps1"
)

$requiredPaths += $invoicecraftPaths

$mailhealthPaths = @(
    "apps/mailhealth/package.json",
    "apps/mailhealth/nuxt.config.ts",
    "apps/mailhealth/app/app.vue",
    "apps/mailhealth/app/components/MailHealthHome.vue",
    "apps/mailhealth/app/components/LanguageNav.vue",
    "apps/mailhealth/app/components/LegalFooter.vue",
    "apps/mailhealth/app/components/SiteHeader.vue",
    "apps/mailhealth/app/data/copy.ts",
    "apps/mailhealth/app/data/locales.ts",
    "apps/mailhealth/app/data/pages.ts",
    "apps/mailhealth/app/data/routes.ts",
    "apps/mailhealth/app/data/tools.ts",
    "apps/mailhealth/app/pages/index.vue",
    "apps/mailhealth/app/pages/[locale]/[page].vue",
    "apps/mailhealth/app/pages/[locale]/index.vue",
    "apps/mailhealth/app/pages/[locale]/tools/[slug].vue",
    "apps/mailhealth/app/utils/analytics.ts",
    "apps/mailhealth/server/routes/sitemap.xml.ts",
    "apps/mailhealth/tests/mailhealth.test.ts",
    "tests/e2e/mailhealth.spec.ts",
    "scripts/validate-mailhealth-preview.ps1"
)

$requiredPaths += $mailhealthPaths

$sitepulsePaths = @(
    "apps/sitepulse-lab/package.json",
    "apps/sitepulse-lab/nuxt.config.ts",
    "apps/sitepulse-lab/app/app.vue",
    "apps/sitepulse-lab/app/components/SitePulseHome.vue",
    "apps/sitepulse-lab/app/components/LanguageNav.vue",
    "apps/sitepulse-lab/app/components/LegalFooter.vue",
    "apps/sitepulse-lab/app/components/SiteHeader.vue",
    "apps/sitepulse-lab/app/data/copy.ts",
    "apps/sitepulse-lab/app/data/locales.ts",
    "apps/sitepulse-lab/app/data/pages.ts",
    "apps/sitepulse-lab/app/data/routes.ts",
    "apps/sitepulse-lab/app/data/tools.ts",
    "apps/sitepulse-lab/app/pages/index.vue",
    "apps/sitepulse-lab/app/pages/[locale]/[page].vue",
    "apps/sitepulse-lab/app/pages/[locale]/index.vue",
    "apps/sitepulse-lab/app/pages/[locale]/tools/[slug].vue",
    "apps/sitepulse-lab/app/utils/analytics.ts",
    "apps/sitepulse-lab/server/routes/sitemap.xml.ts",
    "apps/sitepulse-lab/tests/sitepulse.test.ts",
    "tests/e2e/sitepulse.spec.ts",
    "scripts/validate-sitepulse-preview.ps1"
)

$requiredPaths += $sitepulsePaths

$pixelbatchPaths = @(
    "apps/pixelbatch/package.json",
    "apps/pixelbatch/nuxt.config.ts",
    "apps/pixelbatch/app/app.vue",
    "apps/pixelbatch/app/components/PixelBatchHome.vue",
    "apps/pixelbatch/app/components/LanguageNav.vue",
    "apps/pixelbatch/app/components/LegalFooter.vue",
    "apps/pixelbatch/app/components/SiteHeader.vue",
    "apps/pixelbatch/app/data/copy.ts",
    "apps/pixelbatch/app/data/locales.ts",
    "apps/pixelbatch/app/data/pages.ts",
    "apps/pixelbatch/app/data/routes.ts",
    "apps/pixelbatch/app/data/tools.ts",
    "apps/pixelbatch/app/pages/index.vue",
    "apps/pixelbatch/app/pages/[locale]/[page].vue",
    "apps/pixelbatch/app/pages/[locale]/index.vue",
    "apps/pixelbatch/app/pages/[locale]/tools/[slug].vue",
    "apps/pixelbatch/app/utils/analytics.ts",
    "apps/pixelbatch/app/utils/pixelbatchWorker.ts",
    "apps/pixelbatch/app/workers/pixelbatch.worker.ts",
    "apps/pixelbatch/server/routes/sitemap.xml.ts",
    "apps/pixelbatch/tests/pixelbatch.test.ts",
    "tests/e2e/pixelbatch.spec.ts",
    "scripts/validate-pixelbatch-preview.ps1"
)

$requiredPaths += $pixelbatchPaths

$docshiftPaths = @(
    "apps/docshift/package.json",
    "apps/docshift/nuxt.config.ts",
    "apps/docshift/app/app.vue",
    "apps/docshift/app/components/DocShiftHome.vue",
    "apps/docshift/app/components/LanguageNav.vue",
    "apps/docshift/app/components/LegalFooter.vue",
    "apps/docshift/app/components/SiteHeader.vue",
    "apps/docshift/app/data/copy.ts",
    "apps/docshift/app/data/locales.ts",
    "apps/docshift/app/data/pages.ts",
    "apps/docshift/app/data/routes.ts",
    "apps/docshift/app/data/tools.ts",
    "apps/docshift/app/pages/index.vue",
    "apps/docshift/app/pages/[locale]/[page].vue",
    "apps/docshift/app/pages/[locale]/index.vue",
    "apps/docshift/app/pages/[locale]/tools/[slug].vue",
    "apps/docshift/app/utils/analytics.ts",
    "apps/docshift/app/utils/docshiftWorker.ts",
    "apps/docshift/app/workers/docshift.worker.ts",
    "apps/docshift/server/routes/sitemap.xml.ts",
    "apps/docshift/tests/docshift.test.ts",
    "tests/e2e/docshift.spec.ts",
    "scripts/validate-docshift-preview.ps1"
)

$requiredPaths += $docshiftPaths

$missing = @()
foreach ($path in $requiredPaths) {
    if (-not (Test-Path -LiteralPath $path)) {
        $missing += $path
    }
}

if ($missing.Count -gt 0) {
    $missing | ForEach-Object { Write-Error "Missing required path: $_" }
    throw "Required repository structure is incomplete."
}

$adrCount = (Get-ChildItem -Path "docs/ADR" -Filter "*.md" -File | Measure-Object).Count
if ($adrCount -lt 12) {
    throw "Expected at least 12 ADR files, found $adrCount."
}

Write-Host "Required repository structure is present."
